### ISSUE TITLE
Make cleaning options page

### ISSUE THREAD

**Issue by Alastairm** [Alastairm/django_env#1]
Need to make a page that:
* shows error in rows / columns
 *  gives the ability to edit / remove these rows
* can specify custom delimiter

**Comment by lilfolr** [comment]
I am free to work on this tomorrow [14 sep], so if you have set up such a page by then please push the changes and let me know, otherwise ill start one from scratch.

**Comment by Alastairm** [comment]
was just migrating the todo list from the readme. I'm also free tomorrow
arvo to work on it. I was going to work on integrating the accounts with
upload, but I just realised that's kinda dependent on the options pages.
Perhaps we could meet up to discuss the approach?

Cheers

**Comment by lilfolr** [comment]
Yep, sure. I'm in uni tomorrow from 13:00. I do need to spend some time on another assignment, but I'm happy to spend some time getting a plan together.

**Comment by Alastairm** [comment]
I'm in CS2.02 at the moment, so come by whenever you're free

**Comment by Alastairm** [comment]
The page will need to page changes to the list of column objects - details of them are below:
    Variables:
    most_common -- <= 15 most common results within the column values.
    least_common -- <= 15 least common results within the column values.
    empty -- Boolean value of whether the column holds values or not.
    header -- Column header/title.
    type -- The type of data in column, e.g., String, Float, Integer,
        Enumerated.
    values -- List of CSV values for the column.
    analysis -- Analysis object associated with this column.

def __init__(self, header=''):
        self.most_common = []
        self.least_common = []
        self.empty = False
        self.header = header
        self.type = ''
        self.values = []
        self.analysis = None
        self.total_true = 0
        self.total_false = 0
        self.total_yes = 0
        self.total_no = 0
        self.data_size = -1
