### ISSUE TITLE
Group Errors

### ISSUE THREAD

**Issue by lilfolr** [Alastairm/django_env#10]
* When report is generated, if there are multiple instances of the same error collapse them down [possibly with an option to expand to details]
* Collapse report sections

**Comment by lilfolr** [comment]
@Alastairm @Alastairsc  Are we going to make a 'dynamic' report page, or are we going to give the users options, then load up the static page?
I dont want to spend time editing the static page if it's going to replaced with a django one down the line.

**Comment by Alastairsc** [comment]
whatever easier really, we dont have much time. I would prefer a static page just because it would also work for the executable while a django page would only work for uploaded files and its the bigger files that need more customization when it comes to report generation

**Comment by lilfolr** [comment]
Cool. I'll edit the static one then.

**Comment by lilfolr** [comment]
Done.
