### ISSUE TITLE
Template explanation

### ISSUE THREAD

**Issue by Alastairsc** [Alastairm/django_env#13]
Ive written an explanation about how the templates work on the google drive. Could one of you make a new page and put the expalantion on it? just up 'until the how to write templates part'. Also the underlined parts need a link to the document, either on another page or a link to download the word/pdf document. After that you should put links to that page anywhere the options for templates are so users dont get confused

**Comment by lilfolr** [comment]
Is that the "Template Format" document?
I can put that on the page where you make templates from scratch if you want?

**Comment by Alastairsc** [comment]
thats fine, anywhere easy to find for users
