### ISSUE TITLE
Bugs found

### ISSUE THREAD

**Issue by Alastairsc** [Alastairm/django_env#19]
Dont let column number go below 1
Upload template button missinng
Display header row while correcting invalid rows so users know what to correct to
Quotation marks are required while editing rows - either make it easier or tell users that and catch the error it causes
Put link back to upload page on report so if users want to go back and customize or upload/ make a template
check for errors when customizing and specifying all columns

**Comment by Alastairsc** [comment]
Also remove types that are unsupported from any lists you have of the data types

**Comment by Alastairm** [comment]
I assume Display headers while correcting invalid rows is actually while correcting cell errors? Rows don't have headers.

**Comment by Alastairm** [comment]
Cell errors now displays column headers, though it display columns twice as the headers have had "(Column N)" appended to them
