### ISSUE TITLE
Dont let column number go below 1

### ISSUE THREAD

**Issue by Alastairm** [Alastairm/django_env#20]
could I get some context for this?
how do I recreate the issue?
what page is it occurring on?

**Comment by Alastairsc** [comment]
in the create upload page, when choosing a column number you can go 0 and even negative

**Comment by Alastairsc** [comment]
seems to be just the set type column part, not the range part

**Comment by lilfolr** [comment]
I can fix it.

**Comment by lilfolr** [comment]
Completed

**Comment by Alastairm** [comment]
This is also an issue for headers & data start (& anything else with line numbers)
