### ISSUE TITLE
check for errors when customizing and specifying all columns

### ISSUE THREAD

**Issue by Alastairm** [Alastairm/django_env#24]
Not too sure what this means...

**Comment by Alastairsc** [comment]
melinda home some error when she tried to do it
I dunnno, just make sure you test it for incorrect user inputs

**Comment by Alastairsc** [comment]
had*

**Comment by Alastairm** [comment]
I assume this the datatypes page because the error correcting pages will just keep the row/cell as an error if invalid input is submitted. 
It's no possible to submit an invalid form per se on the datatypes page as it's all drop down lists. Of course it's possible to change a column to a type which the data is not, to check for that we'd really need it to happen in the analyser.

**Comment by Alastairsc** [comment]
might have been because she tried so assign some columns as characters and dates

**Comment by Alastairm** [comment]
ahhh well in that case that's fixed - there's a Data.types variable name in data.py that contains all the valid types & what name they're given on the website, and references to types on the website use that (i.e. if available types gets updated that should  be too).
