### ISSUE TITLE
remove types that are unsupported

### ISSUE THREAD

**Issue by Alastairm** [Alastairm/django_env#25]
Also remove types that are unsupported from any lists you have of the data types
Which types are listed that are unsupported?
(I just copied the types from those listed in data.define_types)

**Comment by lilfolr** [comment]
Ill remove the unused types from the template generator too (when we figure out what they are)

**Comment by Alastairm** [comment]
the supported types are in the Data.types variable in data.py

**Comment by lilfolr** [comment]
Ok. For the record, those are:
* Ignored
* Numeric
* Integer
* Float
* Sci_Notation
* Boolean
* String
* Enum
* Identifier
* Email

**Comment by Alastairm** [comment]
yup, at this point in time (not sure if it's subject to change RE dates etc.)

**Comment by lilfolr** [comment]
I have removed the invalid ones from the create template doc, and i think that the other references have been updated.

**Comment by lilfolr** [comment]
Do we support currency? It's in the final report, but not in data.types.

**Comment by Alastairm** [comment]
yup looks like we do, I must have missed it sorry.
It also appears Date & Time are back in there now.

**Comment by lilfolr** [comment]
Added extra types in the template generator
