### ISSUE TITLE
Deploy site with Apache

### ISSUE THREAD

**Issue by Alastairm** [Alastairm/django_env#6]

**Comment by Alastairm** [comment]
or possibly Nginx & Gunicorn
http://trevore.com/post/building-blog-django-17-and-python-34-part-2

**Comment by lilfolr** [comment]
I'll have a look

**Comment by lilfolr** [comment]
I have installed and (attempted to) configure nginx and gunicorn. I am getting the server to run, however any attempt to load the pages give the error:
> AttributeError: 'module' object has no attribute 'ROOT_URLCONF'

I'll have another look tomorrow and see if i can fix it.

**Comment by lilfolr** [comment]
I have managed to get the gunicorn server running.
Is it currently running on port 8081, both public and private.
http://uwadataanalysis.cloudapp.net:8081/
When we have tested it I can migrate it to the default port 80.
